### ISSUE TITLE
Add links (both directions) between main website and https://kubernetes.dev/

### ISSUE THREAD

**Issue by sftim** [kubernetes/contributor-site#159]
Mirror image of https://github.com/kubernetes/website/issues/23417

**Comment by sftim** [comment]
Also relevant to #202

**Comment by CIPHERTron** [comment]
Heyy @sftim can I get some more context on this issue?
Thanks!

**Comment by sftim** [comment]
For more context, read https://github.com/kubernetes/website/issues/23417

I'll close this one.
/close
