### ISSUE TITLE
Dead link to mentoring initiatives in the Getting started doc

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/contributor-site#175]
Hi,

looks like the link to the mentoring initiatives in the Getting started page is broken:

![image](https://user-images.githubusercontent.com/4662360/99228150-8611a300-27ec-11eb-9129-74514e889c52.png)

![image](https://user-images.githubusercontent.com/4662360/99228199-932e9200-27ec-11eb-8504-47d48633be87.png)

**Comment by mrbobbytables** [comment]
Sorry this took so long to catch up to.
The upstream link in k/community does work so this is an issue with the parser. I have an idea as what the cause is. (The link has some additional unseen whitespace on the end) and can revisit later.
 
/kind bug

**Comment by davideimola** [comment]
Hi @mrbobbytables ,
I have watched this issue. I think I might help... I can create a PR on the community repository by removing the unseen whitespace.
After that, I can insert that document in the external-sources too!

What do you think?
