### ISSUE TITLE
Create new top level Community section

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/contributor-site#201]
The community page will house our other documentation like our CoC, values, potentially mentoring etc.

To start, it should at a minimum have our CoC and values.

/kind feature

**Comment by davideimola** [comment]
Hi @mrbobbytables,
I am not so sure how to handle this section https://www.kubernetes.dev/resources/.
I think the community section duplicates in part the resources one.

Can you help me to understand the topic we want to move out from the resources one?

**Comment by mrbobbytables** [comment]
Sure!
We will move some of the content (code of conduct and community groups) that are currently under resources to the new community section, as that is a better home for it. :)
The top level sections should be ordered (weighted) as follows:
- Welcome
- Blog
- Docs
- Community
- Resources
- Events

In the new community section, I'd order the pages like:
- community groups
- mentoring
- values 
- code of conduct
