### ISSUE TITLE
Make contributor site findable

### ISSUE THREAD

**Issue by jberkus** [kubernetes/contributor-site#202]
I've lost the URL for the contributor site, and found that there was no way to get to it if you don't already have the URL.  There's no link to it from kubernetes.io that I can find, and its google rank is apparently 0.

We need to work on findability for the site if we expect it do do any good.  This would include:

1. Linking from home page or community page of kubernetes.io
2. Linking from CNCF contributor page
3. Developing pattern for contributor comms that works as (1) add page to contributor site (2) make announcement that links to contributor site instead of putting content elsewhere

**Comment by sftim** [comment]
https://kubernetes.io/docs/contribute/ is a guide to contributing to Kubernetes _documentation_.

I'd like to redirect https://kubernetes.io/docs/contribute/ to https://www.kubernetes.dev/docs/guide/ but there's a problem: localization. https://kubernetes.io/docs/contribute/ is localized; https://www.kubernetes.dev/docs/guide/ is not. If we take the naive approach, we discard all the downstream localizations of https://kubernetes.io/docs/contribute/ _and_ we don't have a good home for them afterwards.

I welcome suggestions on ways forward, without requiring that https://www.kubernetes.dev/ adopts localization. I'm [_all for_ localizing https://www.kubernetes.dev/](https://github.com/kubernetes-sigs/contributor-site/issues/167), but that's going to need a lot of interest from people with the skills and the time to help out.

**Comment by mrbobbytables** [comment]
> I welcome suggestions on ways forward, without requiring that https://www.kubernetes.dev/ adopts localization. I'm [_all for_ localizing https://www.kubernetes.dev/](https://github.com/kubernetes-sigs/contributor-site/issues/167), but that's going to need a lot of interest from people with the skills and the time to help out.

Multiple groups have shown interest in localizing that content - The first real step will be to migrate the repo to the kubernetes org so we can reuse teams. There are a few other reason for that migration, but easier localization is a big one.

**Comment by jberkus** [comment]
/remove-lifecycle stale

This is still an issue.

**Comment by jberkus** [comment]
/remove-lifecycle stale

This is still unfixed

**Comment by chris-short** [comment]
@parispittman Can you share access to the Google Search Console for kubernetes.dev? I need to figure out if what we're doing is helping or not and that's usually the best place.

**Comment by sftim** [comment]
I'm OK with seeing this issue reopened.

**Comment by chris-short** [comment]
Without additional data from the search engine webmaster tools I'm not sure we can assess what we've done to date has worked or not. I'm fine putting on my SEO hat if I can get access to the tools that help measure change. More specifically..

[https://search.google.com/search-console](https://search.google.com/search-console)

[https://www.bing.com/webmasters/](https://www.bing.com/webmasters/)

There is a Google Site Verification DNS TXT record that exists for k8s.dev which leads me to believe there's already a registration there. Access can be shared with other goog accounts I believe here: https://search.google.com/search-console/users
