### ISSUE TITLE
Include design principles

### ISSUE THREAD

**Issue by sftim** [kubernetes/contributor-site#207]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/principles.md is an (incomplete) list of Kubernetes design principles. We should give it a home within https://k8s.dev/

/kind feature

**Comment by mrbobbytables** [comment]
Copying from slack:
We don’t plan on publishing anything out of design-proposals directory directly. It’s up to sig-arch to review the relevant documentation and move it over to the devel directory.

We do plan to publish the contents from the devel directory once its reviewed for accuracy

For more information see: https://github.com/kubernetes/community/issues/2565
