### ISSUE TITLE
CNCF Code of Conduct link leads to a 404 page

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes/contributor-site#229]
The CNCF Code of Conduct link on this page https://www.kubernetes.dev/welcome/ leads to a 404 web page - https://www.kubernetes.dev/resources/code-of-conduct/ . Has it moved?

I see the code of the welcome page is here - https://github.com/kubernetes/contributor-site/blob/master/content/en/welcome/_index.md

Probably we need to link to this - https://www.kubernetes.dev/community/code-of-conduct/ ? or this - https://github.com/cncf/foundation/blob/master/code-of-conduct.md ? or this - https://kubernetes.io/community/static/cncf-code-of-conduct/ ?

or maybe link to this - https://github.com/kubernetes/contributor-site/blob/master/code-of-conduct.md ?

**Comment by karuppiah7890** [comment]
Noticed a reference here too - https://github.com/kubernetes/contributor-site/blob/master/code-of-conduct.md

**Comment by karuppiah7890** [comment]
@palnabarun ^ Could you help here?

**Comment by karuppiah7890** [comment]
I'll raise a PR for this with this link https://www.kubernetes.dev/community/code-of-conduct/ , assuming we don't want folks to go to a different site and stay within the same site https://www.kubernetes.dev

**Comment by palnabarun** [comment]
I see that earlier it was linked to https://github.com/cncf/foundation/blob/master/code-of-conduct.md in https://github.com/kubernetes/contributor-site/commit/b6e060ffd077dbdf92a6f7f0b10b74de27dd8bc2.

Although if the intent is to redirect through https://k8s.dev/community/code-of-conduct, that also is a good approach.

@karuppiah7890 -- Please feel free to raise a PR with that change. Thank you! 👍🏽

**Comment by karuppiah7890** [comment]
I was wondering why there are so many places where code of conduct is maintained

**Comment by karuppiah7890** [comment]
I would have expected one source of truth - one codebase and one site, and everyone else linking to it in some way
