### ISSUE TITLE
Regarding:  Backlink for Org Membership Request form on the website

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes/contributor-site#241]
The backlink for Org Membership Request form in the website [here](https://www.kubernetes.dev/resources/services/#organization-membership), is redirecting to an empty template [here](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) which actually should redirect to the provided template [here](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)

**Comment by Atharva-Shinde** [comment]
kind/bug
kind/cleanup

**Comment by Atharva-Shinde** [comment]
remove /kind bug

**Comment by Debanitrkl** [comment]
TODO:
Update the link on `line 49` of this [file ](https://github.com/Debanitrkl/contributor-site/blob/master/content/en/resources/services.md) and replace it with this [link](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)
/good-first-issue

**Comment by Atharva-Shinde** [comment]
I know @Debanitrkl  which file the changes needs to be done,  I am currently exploring the codebase of the contributors website and then get the issue done

**Comment by CIPHERTron** [comment]
Heyy @Atharva-Shinde any updates on this?

Also, I'm not quite sure if this issue still persists because the **Org Membership Request** form present [here](https://www.kubernetes.dev/resources/services/#organization-membership) takes me to the right form. Are you referring to some other form? 🤔

**Comment by Atharva-Shinde** [comment]
Yeah I'll close this as the pr was merged

**Comment by Atharva-Shinde** [comment]
The one you are seeing is the updated backlink of the org membership form, which was updated through this issue's pr
