### ISSUE TITLE
Add blog on using Mermaid to create diagrams

### ISSUE THREAD

**Issue by chrismetz09** [kubernetes/contributor-site#250]
Hey k8s.dev folks-
Promoting use of Mermaid-created diagrams for K8s docs. @sftim suggested creating a blog on this topic for docs contributors, new and experienced. Diagrams enhance docs clarity, quality and reader-friendlinesss. IMHO, contributors should consider using diagrams if and where appropriate.

Here is markdown version of the blog. Thoughts!

https://github.com/chrismetz09/K8s-mermaid-blog/blob/main/README.md

**Comment by chrismetz09** [comment]
@sftim, got it. Where should I open PR?

**Comment by chrismetz09** [comment]
@sftim, I'll try contributor-site first.

**Comment by CIPHERTron** [comment]
I think this issue can be closed now.
Thanks @chrismetz09 ❤️ 

/close
