### ISSUE TITLE
SIG ContribEx weekly marketing meeting is listed twice

### ISSUE THREAD

**Issue by sreekaransrinath** [kubernetes/contributor-site#251]
Screenshot:
![image](https://user-images.githubusercontent.com/50989977/139250092-9dca6c3e-2fb6-40da-a5be-047804f52e50.png)

https://www.kubernetes.dev/resources/calendar/

**Comment by CIPHERTron** [comment]
Heyy @sreekaransrinath, thanks for bringing this to our notice. This needs to be fixed.

**Comment by mrbobbytables** [comment]
It's been fixed 👍 

/close
