### ISSUE TITLE
Inaccurate descriptions on the Kubernetes Community Values

### ISSUE THREAD

**Issue by sreekaransrinath** [kubernetes/contributor-site#252]
The pages describing the Kubernetes Community Values have subtitles/descriptions as "Mentoring Initiatives"
![image](https://user-images.githubusercontent.com/50989977/139255451-38ab2def-9e6d-427b-930a-4950509a5dcc.png)
![image](https://user-images.githubusercontent.com/50989977/139255546-4e33a92f-3889-4b12-8ff4-de6f5aa9a971.png)

"The values that make up the Kubernetes Community" or something similar may be a better fit here

**Comment by alisondy** [comment]
Thanks for sorting this out @sreekaransrinath , Closing this issue as the issue has been resolved 💯

/close
