### ISSUE TITLE
kubernetes/org link in `/resources/service` points to a wrong repo

### ISSUE THREAD

**Issue by CIPHERTron** [kubernetes/contributor-site#253]
The link of the `kubernetes/org` hyperlink points to the wrong repository. Currently, it points to [this](https://github.com/org) random repo whereas actually, it should point to https://github.com/kubernetes/org
![Screenshot from 2021-11-04 04-13-42](https://user-images.githubusercontent.com/56754747/140222114-13200c8d-9267-4cb5-92ba-6f837cfc9da1.png)

/kind bug
/good-first-issue

**Comment by CIPHERTron** [comment]
How to fix this:
We actually have two instances of this bug in the same section because both are linked to the same variable. To fix both of this, we have to change the link of the `kubernetes/org` variable present in **Line 222** of [content/en/resources/services.md](https://github.com/kubernetes/contributor-site/blame/master/content/en/resources/services.md) file from https://github.com/org to https://github.com/kubernetes/org

**Comment by sreekaransrinath** [comment]
I'd like to take this on -- /assign

**Comment by sreekaransrinath** [comment]
I'm actually pretty swamped for the next couple of days -- if any other new contributor wants to take over by then, please be my guest and submit a PR. If it's still open when I check back, I'll take care of it :)

**Comment by chetak123** [comment]
Hey @sreekaransrinath I am going to make a PR for this issue.

**Comment by CIPHERTron** [comment]
> I'm actually pretty swamped for the next couple of days -- if any other new contributor wants to take over by then, please be my guest and submit a PR. If it's still open when I check back, I'll take care of it :)

That's completely fine @sreekaransrinath 💯 
/unassign @sreekaransrinath

**Comment by CIPHERTron** [comment]
> Hey @sreekaransrinath I am going to make a PR for this issue.

Thanks for your contributions @chetak123 🎉 
/assign @chetak123

**Comment by CIPHERTron** [comment]
#254 fixes this issue. Thus closing!
