### ISSUE TITLE
Articles publishing too early

### ISSUE THREAD

**Issue by sftim** [kubernetes/contributor-site#281]
https://kubernetes.dev/blog/2022/01/10/meet-our-contributors-india-ep-01/ was intended to publish next week; however, it is already live.

I assume this is a bug.

/kind bug

**Comment by jberkus** [comment]
/remove-lifecycle rotten

This is still a bug

**Comment by chris-short** [comment]
According to https://github.com/kubernetes/contributor-site/blob/master/.github/workflows/netlify-periodic-build.yml runs at 3:30 UTC daily (thus the blog uses UTC time). You have to use \[\*\*Hugo front matter\*\*\](https://gohugo.io/content-management/front-matter/) to establish the date you want to publish your article and set the time to 0330 UTC or earlier, then it should get published.  
  
What's happening \*now\* that's outside of that current setup?

**Comment by mrbobbytables** [comment]
The config is set to build future, so it ignores the date and builds everything. The makefile just has to be updated to remove that command
https://github.com/kubernetes/contributor-site/blob/master/Makefile#L128

**Comment by sftim** [comment]
If anyone wants to work on this, I'm happy to explain in detail what the fix could look like.

**Comment by imnmo** [comment]
Hi, Can I work on this issue?

**Comment by chris-short** [comment]
Yes, feel free. You don’t need permission. Make sure you follow the steps in the contributor guide to get yourself ready to commit: https://www.kubernetes.dev/docs/guide/

**Comment by imnmo** [comment]
Hi Folks,

I have figured out the solution. 

Addressing the actual issue by @sftim  with article publishing early than the intended date. My assumption is there is no such feature to schedule posts - I looked up the GH workflow as pointed by @chris-short and it runs daily and just builds them, no special job or stage to schedule posts.

The only option is to understand how Hugo handles scheduling future posts. @mrbobbytables gave the right direction to check the `hugo --buildFuture` - which Hugo enforces to build the future posts for the enabled **PublishDate** blog posts (see here: https://gohugo.io/content-management/front-matter/)

So, the solution is to: 

- Disable the --build future flag in the production-build stage in the makefile & 
- Enable the **PublishDate** option for any later dated posts - needs support to change this process in the Markdown template
- --build future could be untouched for other stages to preview the post. 

It works. I tested locally for posts with the PublishDate (set to today+1) option for a test blog post, based on PublishDate Hugo will not publish and waits until the publishDate is today and the netlify build job runs to publish them. So this could be the option for us to schedule the post for a future date after the PR merge.

Please let me know about this solution. We can discuss this for further clarifications. Once all is good. I will provide the PR for the same. 

(Thanks, @chris-short  for giving hints during the weekly SIG Marketing meeting)

**Comment by sftim** [comment]
Thanks @imnmo 

Please open that PR with a proposed fix. I'll be happy to review it (might not be the same day; sorry about that).

**Comment by sftim** [comment]
@imnmo, could we help you get working on a fix? It's OK to ask for help.

**Comment by imnmo** [comment]
@sftim unfortunately, I didn't find time past week to provide the PR. I will work on this issue today and create PR for discussions.

**Comment by imnmo** [comment]
Can anyone help me close this issue? I can't, but the PR is merged and can be closed.
