### ISSUE TITLE
Feature Request: A section that gives a high-level overview of the Kubernetes project (targeted towards new contributors)

### ISSUE THREAD

**Issue by tahsintunan** [kubernetes/contributor-site#285]
For new contributors (esp. if they are new to open source projects), understanding such a big codebase may seem daunting. There should be a section that walks us through the codebase and gives us a **high-level overview**. 

The section should go over the following topics:
- **Codebase Tour**: Goes over the project repo and explains how the project is structured
- **Architecture**: Explains the overall architecture of the project (i.e. why things are the way they are)

This section doesn't have to go too deep into the details. Rather, the goal is to give new contributors a high-level view of the project.

**Comment by jberkus** [comment]
/remove-lifecycle rotten

This is actually a planned feature for the site, so no reason to close the issue.

**Comment by imnmo** [comment]
@mrbobbytables  could you help me with this? I know you are creating the new contributor workshop material and I would be happy to add the content here for new contributors.

**Comment by sftim** [comment]
> This is actually a planned feature for the site, so no reason to close the issue.


/lifecycle frozen

**Comment by imnmo** [comment]
Hi Folks, any help or pointers for this task would be great for me to kick-start. I am still interested in finishing this task.

**Comment by imnmo** [comment]
Update: I got details to proceed with the architecture. It's a seemingly big issue with a chunk of tasks. I will try to create a task list as I move on. Thanks, @mrbobbytables for the heads up.

**Comment by imnmo** [comment]
FYI, for folks interested in reviewing [this](https://deploy-preview-347--kubernetes-contributor.netlify.app/onboarding/) check this rendered content
