### ISSUE TITLE
hard time finding how to contribute to the site itself 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/contributor-site#289]
folks want to update the site itself and having hard time figuring how where to find this repo

"edit this site" with a link here

**Comment by Atharva-Shinde** [comment]
And,
GitHub link at the bottom of [kubernetes.dev](https://www.kubernetes.dev) is redirecting to kubernetes/community repo,
we need  to redirect the link to this i.e kubernetes/contributor-site repository,

this would help in some visibility of this repository

**Comment by Atharva-Shinde** [comment]
And,
GitHub link at the bottom of [kubernetes.dev site](https://www.kubernetes.dev) is redirecting to [kubernetes/community](https://github.com/kubernetes/community) repo, 
which IMO should instead redirect to this repository i.e kubernetes/contributor-site

This would help in gaining some visibility of this repo

**Comment by Atharva-Shinde** [comment]
the crux is almost all content on this website is not hardcoded in this repo itself. This content is present in either k/website or k/community or similar other repos.
for example: [The Contributors CheatSheet section](https://www.kubernetes.dev/docs/contributor-cheatsheet/) is imported from [here](https://github.com/kubernetes/community/blob/997e52b172786d3f32f1c76781689b06c2b374e6/contributors/guide/contributor-cheatsheet/README.md)

**Comment by mrbobbytables** [comment]
When we looked into this previously, the only good way of doing it was adding an additional frontmatter item with its original location and render that in the footer or something along those lines.

**Comment by jberkus** [comment]
/remove-lifecycle rotten

I think the immediate solution to this is to have a page on the site about how to contribute to the site, which exposes the complexity.

The eventual solution is to have allmost all of the contents of the site all live in one repo.

**Comment by Atharva-Shinde** [comment]
+1 somewhere in the documentation section for now

**Comment by sreekaransrinath** [comment]
Is this issue still open to work on?

@Atharva-Shinde mind if I take over and implement @jberkus' suggestions?

**Comment by Atharva-Shinde** [comment]
Sure@sreekaransrinath, a page describing the structure of this repo would be useful for new contributors
