### ISSUE TITLE
CONTRIBUTING.md additions for this repo

### ISSUE THREAD

**Issue by parispittman** [kubernetes/contributor-site#290]
need:
- how to build locally
- how to test
- how to preview
- who to contact / sig contribex info

**Comment by Atharva-Shinde** [comment]
The guide on how to set up and run the site locally is in the [Readme.md](https://github.com/kubernetes/contributor-site#running-the-site-locally) file of this repository

**Comment by Atharva-Shinde** [comment]
The guide on how to set up and run the site locally is already in the [Readme.md](https://github.com/kubernetes/contributor-site#running-the-site-locally) file of this repository
