### ISSUE TITLE
place to host annual reports

### ISSUE THREAD

**Issue by parispittman** [kubernetes/contributor-site#312]
need a place to host annual report summaries on the site - k8s.dev/reports?

last year - https://github.com/kubernetes/steering/blob/main/reports/summary-2020.md
this year - https://github.com/kubernetes/steering/blob/main/reports/summary-2021.md

**Comment by jberkus** [comment]
I'd say resources/annualreports/

**Comment by jberkus** [comment]
Closing this; if someone feels like copying over the annual reports, they can just do it and create a PR.

/close

**Comment by parispittman** [comment]
@jberkus can we keep it open with a help wanted label then?

**Comment by jberkus** [comment]
Better to open a new issue to actually add the annual reports.
