### ISSUE TITLE
Re-arrange Contributor Summit to be self-archiving

### ISSUE THREAD

**Issue by jberkus** [kubernetes/contributor-site#316]
How it is now:

Currently the contributor-summit section of the website looks like this:

```
events/
  kseu/
past events/
  2021/
    kseu/
    ksna/
  2020/
```

... this means that we have to go through a process of "archiving" each Summit, which not incidentally breaks any links anyone made to the original summit pages.

What we should have is something like this

```
events/
  summits/
     2022/
       eu/
       na/
     2021/
     2020/
  other/
    2022/
    2021/
```

events/_index.md would have a list of upcoming events (manually updated, unless we have a way to automate it)

summits/_index.md that would redirect people to the current Summit.  

events/other is for any "other" contributor events.  Currently we don't have pages for anything else, but we might in the future.

@mrbobbytables @Atharva-Shinde

**Comment by Atharva-Shinde** [comment]
/kind feature 
looking into it 👀

**Comment by jberkus** [comment]
```
    2022
      eu/kcs
      na/empty
```

I don't think we need to have a subdir below 2022/eu/ here.  There's only going to be one summit per region per year.

Agreed that we do need subdirs for "others" though.

**Comment by mrbobbytables** [comment]
IMO - we can probably simplify things with
```
events
  2022
    kcseu
    kcsna
  2021
    kcsna
    kcc
  2020
    kcc
```
we then move community meeting to the community section, we can remove office hours and MoC as they are essentially not happening anymore.

**Comment by palnabarun** [comment]
Should we preserve links to existing events? People may be referring to them as permalinks, for example, a link from social media to the Contributor Awards page.

**Comment by jberkus** [comment]
I don't think it's worth the effort to preserve the links.  These are, well, events, and people generally stop caring about them after the event is over.

**Comment by jberkus** [comment]
So, modifying Bob's tree and adding files:

```
events/
  _index.md --> listing of current and recent events
  summit.md --> landing page for whatever the current summit is, mostly redirects
  2022/
    kcseu/
      contents of current events/kcseu/
    kcsna/
      new folder, blank templates
  2021
    kcsna
      contents of events/past-events/2021/kcsna
    kcc
      contents of events/past-events/2021/kcc2021
  2020
    kcc
      contents of events/past-events/2020/kcc2020
```

**Comment by mrbobbytables** [comment]
summit.md isn't needed, the most current summit just needs `summit` listed as an alias in its frontmatter to work 👍

**Comment by jberkus** [comment]
changed.
