### ISSUE TITLE
Add Best Practices guide to contributing to Kubernetes

### ISSUE THREAD

**Issue by NitishKumar06** [kubernetes/contributor-site#325]
**This is a Feature Request**

Although experienced developers and new folks are contributing to the K8s project. It can be beneficial especially to all the new folks where we can include a page with the motive of "Best practices in the community" depicting what are the things that should be followed and avoided. For eg. Don't spam, Try before asking, Don't work on an issue that has already been assigned, Be patient, etc.

**Why is this needed**

This page can really be helpful to all the new folks who are looking forward to contributing to the K8s project.

Comments:

If this issue gets accepted, I'd love to work on this issue since I've written a blog on it as well.

**Comment by deveshgoyal1000** [comment]
It is already there.
https://github.com/kubernetes/community/tree/master/contributors/guide

**Comment by deveshgoyal1000** [comment]
It is already there in code of conduct.
https://github.com/kubernetes/community/tree/master/contributors/guide

**Comment by deveshgoyal1000** [comment]
It is already there in contributors guide and code of conduct.

**Comment by NitishKumar06** [comment]
@deveshgoyal1000 I feel like the document is good but it can be enhanced to make it look better by adding the above points mentioned.

**Comment by mrbobbytables** [comment]
I agree with @deveshgoyal1000 we have most of this documented in the guide and the cheatsheet.
We are also adding a "new contributor course" that will take people through the processes step by step based off the [new contributor workshops](https://www.youtube.com/playlist?list=PL69nYSiGNLP3M5X7stuD7N4r3uP2PZQUx) that we used to run at in person events.

**Comment by NitishKumar06** [comment]
@mrbobbytables May I know what topics does the following course covers?
