### ISSUE TITLE
Wrote a blog regarding contributions to Kubernetes

### ISSUE THREAD

**Issue by abs007** [kubernetes/contributor-site#340]
Hi, I wrote a blog regarding how beginners can get started with Kubernetes contributions and I'd like to add this to https://www.kubernetes.dev/

https://abhii85.hashnode.dev/how-to-get-started-with-k8s-contributions

Please leave your reviews and let me know if the blog can be added. Also, let me know if you'd need the blog content in any other format.

**Comment by jberkus** [comment]
Howdy, Abhisman!

Your post is really helpful!  However, it reads more like early draft documentation than like a blog post.  Would you be interested in drafting a post that focuses on one element of how to get started?  Like a post just on "Finding and getting started in a SIG", maybe enriched with some of your own personal experience?

**Comment by abs007** [comment]
Sure, this might take some time but I'll start with it
