### ISSUE TITLE
Domain config cleanup

### ISSUE THREAD

**Issue by chalin** [kubernetes/contributor-site#359]
This is an umbrella issue for domain related issues for this website:

- [ ] #358 - which Netlify DNS supports
- [ ] #356
- [ ] Consider handling redirects using Netlify DNS rather than redirect rules (provided the site is using Netlify DNS): https://github.com/kubernetes/contributor-site/blob/1a8d9c6dff430129d1ab6998b539f8367aa9171e/netlify.toml#L16-L38

**Comment by SD-13** [comment]
Hi @chalin, Can I work on this issue?
