### ISSUE TITLE
Upgrade Hugo and Docsy

### ISSUE THREAD

**Issue by chalin** [kubernetes/contributor-site#360]
The versions of Hugo and Docsy are quite old.

https://github.com/kubernetes/contributor-site/blob/1a8d9c6dff430129d1ab6998b539f8367aa9171e/netlify.toml#L5-L6

For example, Hugo [0.69.2](https://github.com/gohugoio/hugo/releases/tag/v0.69.2) was released in April 2020.

/cc @nate-double-u

**Comment by chalin** [comment]
Why upgrade? E.g., Docsy's current page-feedback feature is incompatible with GA4 (https://github.com/google/docsy/issues/1302). Since UA is being deprecated and this site is being migrated to GA4 (#354), the a new version of Docsy will eventually be needed. (There is a work-around for the page-feedback issue, so the upgrade isn't urgent.)

**Comment by jberkus** [comment]
/remove-lifecycle stale

We were able to upgrade to 0.89, but remain stalled on the upgrade to 110.

**Comment by sftim** [comment]
See the revised PR, #374

**Comment by chris-short** [comment]
We did spend some time on this during the Contributor Summit at KubeCon Chicago. [@jeefy's fork](https://github.com/jeefy/contributor-site/tree/jeefy-update-hugo) has some errors we need to work through but, we've made a step forward here.

**Comment by sftim** [comment]
What still needs to happen before we can call this Done?

**Comment by jeefy** [comment]
I'm back and working through said errors (actually I started from scratch and scrapped my post-lunch hastily-done branch)

Most errors that we encountered at the summit are fixed, and the last thing I'm updating is the Dockerfile. PR inc soon.

**Comment by jeefy** [comment]
Oh duh.

/assign

**Comment by chris-short** [comment]
Were you going to tackle the move from submodules to Hugo Modules? I can do that separately if you'd like.

I also want to update the K8s.dev picture now that we have a big crowd pic for a replacement.

**Comment by jeefy** [comment]
Kinda did it all, see here: https://github.com/kubernetes/contributor-site/pull/456 

Need help with a CSS issue post-migration but otherwise it's all done and clean.

**Comment by stmcginnis** [comment]
Looks like we're up to [Hugo 0.124 now](https://github.com/kubernetes/contributor-site/blob/c9d1a78cbed3609a0db62f410d7bc33d36cbce07/netlify.toml#L6). There is a slightly newer release out, but I think it's just regular dependency management at this point. Follow-on work being done in #456. I think it's safe to close this issue now.

/close
