### ISSUE TITLE
the text of the navbar is colliding with page which looks distorted

### ISSUE THREAD

**Issue by Nitishupkr** [kubernetes/contributor-site#409]
https://www.kubernetes.dev/
![kubernetes1](https://github.com/kubernetes/contributor-site/assets/95420063/8c46faa9-3e18-4382-9aad-fca5d73f2f3c)
Scroll down to see the effect
assign me i will solve this issue

**Comment by jberkus** [comment]
You don't need to be assigned!  Just submit a PR for CSS to fix it.  Thanks!

**Comment by abhijeetgauravm** [comment]
I think this issue can be closed now....because this issue not persist now!
