### ISSUE TITLE
Add SIG Testing Spotlight  article

### ISSUE THREAD

**Issue by fsmunoz** [kubernetes/contributor-site#413]
Add a Spotlight article on SIG Testing.

(Discussed in the July 27th meeting of SIG Contribex Comms)

**Comment by kaslin** [comment]
@sandipanpanda taking this on

**Comment by kaslin** [comment]
Questions shared, awaiting response

**Comment by kaslin** [comment]
Status update from @sandipanpanda on October 6th: The SIG chairs went through the final round of reviews for the QnA responses for the spotlight yesterday. We are done with with the answers, we can now move on to the next step.

**Comment by sandipanpanda** [comment]
Blog draft ready for review.

**Comment by chris-short** [comment]
In HackMD awaiting comments.

**Comment by kaslin** [comment]
Frederico has reviewed the HackMD draft, ready for PR creation.
