### ISSUE TITLE
Add a blog article on the Book Reading Club

### ISSUE THREAD

**Issue by fsmunoz** [kubernetes/contributor-site#414]
@csantanapr has been leading this initiative for some time, and it's an interesting topic to share with others. We should write an article about it and publish it on the site (and possibly on the main website as well).

**Comment by kaslin** [comment]
Initial version target date: early September

**Comment by nitishfy** [comment]
No updates (Sep 1), waiting for the response.

**Comment by mrbobbytables** [comment]
qq - is the book club k8s focused or CNCF ecosystem focused?

**Comment by fsmunoz** [comment]
@mrbobbytables  , this started before the "change" to a CNCF activity, and one of the questions I have there is exactly to what extent anything changed; I'm assuming it's still k8s focused, but @csantanapr will be the one with the answer.

**Comment by kaslin** [comment]
In the CNCF slack, the channel is "kubernetes-book-club," so pretty sure it's Kubernetes focused. Should get more answers in about 2 weeks.

**Comment by fsmunoz** [comment]
This is being tracked with @csantanapr and the new ETA is EO January,

/remove-lifecycle stale
