### ISSUE TITLE
Do a spotlight on SIG Architecture: Production Readiness

### ISSUE THREAD

**Issue by fsmunoz** [kubernetes/contributor-site#437]
As discussed in https://github.com/kubernetes/contributor-site/pull/431 , we could do one spotlight per project, and specifically one about the Production Readiness sub-project.

**Comment by fsmunoz** [comment]
Initial content ready, shared markdown version for author review.

**Comment by AvineshTripathi** [comment]
Removed WIP, scheduled 2 weeks from now, going through the review comments

**Comment by chris-short** [comment]
Fredrico says it should be published next week. Feedback was given: https://github.com/kubernetes/website/pull/43474

**Comment by chris-short** [comment]
PR has been merged, and post should be published on the 2nd of November.
