### ISSUE TITLE
Addition of "Slack channels overview" page

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/contributor-site#438]
Yesterday, i was going through Cilium project documentation and i found this page very helpful. A page where an overview of different different slack channels is given. Wouldn't it be better if a similar kind of page is also added to K8s Contributor site (K8s community is much much bigger than Cilium, still there isn't any slack channels guide here in K8s). Slack link of K8s is provided everywhere, but there isn't any guide that says, which channels to join in K8s Slack. I think there should be a page in K8s Contributor site that gives overview about different K8s Slack channels.

![Screenshot_2023-09-23-15-10-20-205_com android chrome](https://github.com/kubernetes/contributor-site/assets/116108975/3bf60079-5305-4d78-aa69-dbe73eaf02e2)
![Screenshot_2023-09-23-15-10-33-290_com android chrome](https://github.com/kubernetes/contributor-site/assets/116108975/baa234a6-1516-4cc0-9c4b-a6e5dc912299)
![Screenshot_2023-09-23-15-10-41-222_com android chrome](https://github.com/kubernetes/contributor-site/assets/116108975/582403c9-d58a-4c90-b93c-3628fd2a3ff0)
![Screenshot_2023-09-23-15-11-06-037_com android chrome](https://github.com/kubernetes/contributor-site/assets/116108975/7d354d29-ae29-48c7-be10-63023abc2695)
![Screenshot_2023-09-23-15-11-10-711_com android chrome](https://github.com/kubernetes/contributor-site/assets/116108975/ee267e0f-acb4-43a1-aebf-17bc2618d536)

**Comment by jberkus** [comment]
/remove lifecycle-rotten

@aj11anuj this is a fun idea, but one challenge is that there are hundreds of channels on Kubernetes slack.  It might work better just to list the most important channels.  Wanna take a try at it, and make a pull request?
