### ISSUE TITLE
Change of "Twitter" icon to "X" icon at footer

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/contributor-site#439]
**This is a Feature Request**

**What would you like to be added/enhanced?**
As everybody knows, Twitter is now under X corp. and its world famous blue bird icon has been changed to "X" icon a long time ago. So, maybe we should update it here in footer too.

**Why is this needed?**
I know everyone likes that blue twitter icon, and twitter is better recognised with that icon. But as company has been renamed to "X" with "X" icon then shouldn't we update it?

**Comment by mrbobbytables** [comment]
We inherit it from the theme. When it changes and we upgrade,  ours will change. There's no need to modify our current site to do such a small change. Especially with most major sites still using the bird.

/close
