### ISSUE TITLE
Add more content to footer

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/contributor-site#441]
**This is a Feature Request**

**What would you like to be added**

There is so much empty space at the footer of the k8s.dev page as compared to other pages. Add contents like the "Documentations, blog, Training, partners, community, case studies", Missing social icons, and the copyright portion.
![image](https://github.com/kubernetes/website/assets/94950988/a8e02b09-81eb-4e0f-b914-51487d93d1cb)

**Comments**

Page to update: https://www.kubernetes.dev/

**Comment by jberkus** [comment]
I agree that it would be good to add more to the footer, first task is deciding what.

**Comment by utkarsh-singh1** [comment]
We could add the header content of community page at the bottom - 
![Screenshot from 2024-03-13 13-54-58](https://github.com/kubernetes/contributor-site/assets/96516301/2fdc9ff7-e6e8-42d2-8cbe-6932b77cb4e3)

**Comment by utkarsh-singh1** [comment]
Header contents seems to overlaped with the Body section.
