### ISSUE TITLE
Building Kubernetes page is not beginner friendly

### ISSUE THREAD

**Issue by adityasamant25** [kubernetes/contributor-site#467]
The [Building Kubernetes](https://github.com/kubernetes/kubernetes/blob/c9158e9a19ef8aaf6c53f6293d1f86371fe8e8a6/build/README.md) page is not beginner friendly.

I have been trying to make a containerised build work on my Local Mac laptop for 2 days without success.

The following items need better explaining in my opinion

1. Pre-requisites: 
For the Docker Desktop, it is not sufficient to mention a requirement of 8 GB memory for the Docker VM.. There should be a mention for minimum CPU and Storage allocation to the Docker VM.
Example: My Docker VM had 60 GB of storage allocated to it and the unit test executions failed with `No space left on device `errors.
I increased it to 120 GB and I was able to overcome the space issue, but I have no idea if 120 GB is recommended or not.
This should be specified in the document.

2. Key scripts:
This section describes the scripts available and what each script does.
However, for a reader who is a beginner, it does not mention the order in which the scripts should be executed or tried.
Example:
If my goal is to run all the unit tests on my local machine, it is enough to directly run `build/run.sh make test`?
Is there any pre-requisite to maybe run `build/run.sh make` first?

There should be a clear step-by-step instruction describing the order in which these scripts should be run for a beginner who has no prior experience in this.
The reader should not have to guess this.

3. There is no troubleshooting section:
Some frequently occurring errors may be documented as a troubleshooting section.
When the unit tests fail, a beginner has no idea where to look for the execution logs or how to troubleshoot the issue.

These points are hampering the experience for a developer who is trying to get his/her local build up and running.

**Comment by BenTheElder** [comment]
The points for 1) are a moving target as the project evolves and many active contributors are building on linux instead, PRs welcome!

> If my goal is to run all the unit tests on my local machine, it is enough to directly run build/run.sh make test?
Is there any pre-requisite to maybe run build/run.sh make first?

No, makefiles can encode ordering requirements (one of the main uses!) it would be unusual to require a manual ordering of make targets.

> When the unit tests fail, a beginner has no idea where to look for the execution logs or how to troubleshoot the issue.

Debugging unit tests isn't exactly in scope for this particular document.
