### ISSUE TITLE
Broken Link in "First-contribution" Page

### ISSUE THREAD

**Issue by arujjval** [kubernetes/contributor-site#470]
There is a broken link in the First contribution page, in the SIG Structure Section

![Screenshot from 2024-01-21 13-46-10](https://github.com/kubernetes/contributor-site/assets/106719640/705c03e1-2c1b-4c3d-bbfc-d58dbefcefc4)

The Broken link is in the last line "weekly meetings", which opens the following page

![Screenshot from 2024-01-21 13-46-25](https://github.com/kubernetes/contributor-site/assets/106719640/0707fe56-7e0f-4f28-bdeb-82625bfb47fe)

Can anyone share the new URL to resolve this?

**Comment by jberkus** [comment]
/remove lifecycle-stale

will fix, thanks.

/assign

**Comment by jberkus** [comment]
/reopen
/assign

link is still broken.  Might be better to link to the README than the gdoc, given.
