### ISSUE TITLE
Spotlight: SIG Scheduling

### ISSUE THREAD

**Issue by mfahlandt** [kubernetes/contributor-site#508]
Got a contact in SIG Scheduling to start moving forward. Owned by: @ArvindParekh

17-May-2024: Questions are being answered, will check in.

24-May-2024: Last few questions are on hold temporarily as SIG Lead changes companies

07-June-2024: Questions are answered draft in markdown can start

**Comment by kaslin** [comment]
Hackmd revisions within the comms team are underway. PR should be created soon.

**Comment by ArvindParekh** [comment]
Closing this, since the spotlight on SIG Scheduling has now been published. 
Ref: https://github.com/kubernetes/contributor-site/pull/520, https://github.com/kubernetes/website/pull/47731

Should've been closed by the pr merge. Anyways,
/close
