### ISSUE TITLE
Kubernetes SIG-network meeting not on the Community Calendar.

### ISSUE THREAD

**Issue by thedtripp** [kubernetes/contributor-site#515]
The Kubernetes SIG-network meeting is not showing up on the [Community Calendar](https://www.kubernetes.dev/resources/calendar/). It should be [Thursdays at 09:00 PT (Pacific Time)](https://zoom.us/j/361123509) (biweekly).

[SIG-Network community page](https://github.com/kubernetes/community/blob/master/sig-network/README.md)

[Meeting Notes and Agenda](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit)

**Comment by jberkus** [comment]
Issue verified; meeting is definitely missing.

**Comment by thedtripp** [comment]
> Issue verified; meeting is definitely missing.

Is this a good first issue? I was looking at some code but it's not clear how one might fix this.

**Comment by jberkus** [comment]
No, the SIG Leads need to fix it.  The meeting calendar invite isn't shared with the community calendar.

**Comment by thedtripp** [comment]
> No, the SIG Leads need to fix it. The meeting calendar invite isn't shared with the community calendar.

Should I try opening an issue with SIG Network?

**Comment by jberkus** [comment]
Sure.   Or ask on Slack.

**Comment by thedtripp** [comment]
Closing this. K8s SIG-Network maintains their own separate calendar.
