### ISSUE TITLE
[content] stuff to surface for current contributors

### ISSUE THREAD

**Issue by parispittman** [kubernetes/contributor-site#60]
- [ ] api-conventions.md (source: gh issues, focus groups)
- [ ] Test debugging docs and other general testing/ci docs (source: survey)
- [ ] Other Devel doc links as resources - maybe list a table of contents? the devel README? (source: survey, gh issues)
- [ ] how to contribute to docs / release notes 
- [ ] community-membership.md (source: survey)
- [ ] About contributor experience (source: survey)
- [ ] KEPs - what they are and where to find them (source: everyone)
Ideal state: python peps
- [ ] How the project is organized
- [ ] Sig list
- [ ] Governance (high level blurb with resource links to full details)
- [ ] Subproject OWNERs, approvers, and reviewers 
Think about this group in the next iteration
Rewards and recognition - tbu

Taking from [this doc](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing) and setting as an issue so we can close the doc down.

**Comment by parispittman** [comment]
confirming with github analytics against the community repo that we should definitely surface api-conventions as a first class piece of content on the site. in order of highest views:
api-convention.md
Entire community repo
Architecture
Horizontal pod autoscaler
Entire devel folder
Sig list
Contributor guide
Resource metrics api

**Comment by celanthe** [comment]
Per a conversation with @parispittman--I am going to be taking this on. :)

**Comment by mrbobbytables** [comment]
Specific content can be imported pretty easily. The scripts are in place, the documentation though is not 😬 I'll create an issue to update that.


/remove-lifecycle stale

**Comment by vishakhanihore** [comment]
Hello, @mrbobbytables and @parispittman , I am outreachy applicant and have applied for `Technical Writer`, Can I start contributing to this issue, since there is around a month in results 😄 ?

**Comment by celanthe** [comment]
I'm happy to let @vishakhanihore contribute to this as well @parispittman @mrbobbytables -- It would be nice to have some help! :)

**Comment by celanthe** [comment]
Hi all, just an update, wanted to circle back with @parispittman @mrbobbytables about having @vishakhanihore and I collaborate on this with y'all once things calm down a bit after KubeCon! :) If that sounds good, let me know! :) Looking forward to it and thanks so much!

**Comment by celanthe** [comment]
Hi all--As I'm stepping back from contributing outside of my Storyteller role on the Upstream Marketing team, I've unassigned myself from this issue. Was wondering if @vishakhanihore was still interested in taking it on?

**Comment by sftim** [comment]
I'd like to see the content currently in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md published on https://k8s.dev/ so that it has a stable URI (and there's an opportunity to redirect to it if there is ever a change).

**Comment by sftim** [comment]
Looking at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md I think this is also elevant to people who aren't planning to contribute to Kubernetes (eg: someone writing a CustomResourceDefinition or a controller).

Should that page move to within https://kubernetes.io/ ?
